<?php
// auto-generated by sfSecurityConfigHandler
// date: 2022/09/01 22:14:17
$this->security = array (
  'delete' => 
  array (
    'credentials' => 'administrator',
    'is_secure' => true,
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'translator',
      ),
    ),
    'is_secure' => true,
  ),
  'list' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'translator',
      ),
    ),
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
