<?php
// auto-generated by sfCacheConfigHandler
// date: 2022/09/01 22:14:17
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

