<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/09/01 22:15:09
sfConfig::add(array(
  'mod_sftranslateplugin_enabled' => true,
  'mod_sftranslateplugin_view_class' => 'sfPHP',
));
