<?php
// auto-generated by sfCacheConfigHandler
// date: 2022/09/01 22:14:18
$this->addCache($moduleName, '_popular', array('withLayout' => false, 'lifeTime' => 300, 'clientLifeTime' => 300, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

